[package]
name = "wasi"
version = "0.5.0"
authors = ["The Cranelift Project Developers"]
license = "Apache-2.0 WITH LLVM-exception"
description = "Experimental WASI API bindings for Rust"
edition = "2018"
categories = ["no-std", "wasm"]
keywords = ["webassembly", "wasm"]
repository = "https://github.com/CraneStation/rust-wasi"
readme = "README.md"
documentation = "https://docs.rs/wasi"

[dependencies]
# When built as part of libstd
compiler_builtins = { version = "0.1", optional = true }
core = { version = "1.0", optional = true, package = "rustc-std-workspace-core" }

[features]
# Unstable feature to support being a libstd dependency
rustc-dep-of-std = ["compiler_builtins", "core"]

[badges]
maintenance = { status = "experimental" }
