[package]
name = "wasi"
version = "0.11.0+wasi-snapshot-preview1"
authors = ["The Cranelift Project Developers"]
license = "Apache-2.0 WITH LLVM-exception OR Apache-2.0 OR MIT"
description = "Experimental WASI API bindings for Rust"
edition = "2018"
categories = ["no-std", "wasm"]
keywords = ["webassembly", "wasm"]
repository = "https://github.com/bytecodealliance/wasi"
readme = "README.md"
documentation = "https://docs.rs/wasi"

[workspace]
members = ['crates/witx-bindgen', 'crates/wasi-ephemeral', 'crates/wasi-http']

[workspace.dependencies]
anyhow = "1.0.70"

[dependencies]
# When built as part of libstd
compiler_builtins = { version = "0.1", optional = true }
core = { version = "1.0", optional = true, package = "rustc-std-workspace-core" }
rustc-std-workspace-alloc = { version = "1.0", optional = true }

[build-dependencies]
anyhow = { workspace = true, features = ["std"] }
wit-deps = { version = "0.3.0", features = ["sync"] }

[features]
default = ["std"]
std = []
# Unstable feature to support being a libstd dependency
rustc-dep-of-std = ["compiler_builtins", "core", "rustc-std-workspace-alloc"]

[badges]
maintenance = { status = "experimental" }
